apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270alisonservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270alisonservice
  template:
    metadata:
      name: cit270alisonservice
      labels:
          app: cit270alisonservice
    spec:
      containers:
      - name: cit270alisonservice
        image: gcr.io/mythic-producer-379820/alison-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/for17015@alisonforsberg.cit270.com/"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: alisoncerts
---
# apiVersion: v1
# kind: Service
# metadata:
#  name: cit270alisonservice-loadbalancer
# spec:
# selector:
#     app: cit270alisonservice
#   type: LoadBalancer
#  ports:
#   - port: 443
#     targetPort: 443
#commented out 3/27 to get rid of loadbalancer


---
apiVersion: v1
kind: Service
metadata:
  name: stedi-alisonforsberg-nodeport
spec:
  selector:
    app: cit270alisonservice
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-alisonforsberg-certificate2
spec:
  domains:
    - alisonforsberg.cit270.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-alisonforsberg-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cit270alison
    networking.gke.io/managed-certificates: stedi-alisonforsberg-certificate2
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-alisonforsberg-nodeport
            port:
              number: 80